# Generated by Django 3.2 on 2022-12-30 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'Введите значение от 1 до 10'), django.core.validators.MaxValueValidator(10, 'Введите значение от 1 до 10')]),
        ),
    ]
